--계정생성
DROP USER c##myapp3 CASCADE;
CREATE USER c##myapp3 IDENTIFIED BY 1234 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO c##myapp3; 
GRANT CREATE VIEW, CREATE SYNONYM TO c##myapp3; 
GRANT UNLIMITED TABLESPACE TO c##myapp3; 
ALTER USER c##myapp3 ACCOUNT UNLOCK;